'use client';
import DepartmentPageTemplate, { DeptConfig, ProcessDef } from '../components/DepartmentPageTemplate';

const dept: DeptConfig = {
  id: 'process-quality',
  label: 'Inprocess Quality (IPQC)',
  icon: '⚙️',
  subtitle: 'In-process quality checks, EOL inspection, SPC, red bin analysis, FTT, poka-yoke, traceability',
  headerBg: 'bg-indigo-800',
  headerText: 'text-indigo-300',
  accentBorder: 'border-indigo-500',
  accentBg: 'bg-indigo-50',
  accentText: 'text-indigo-900',
  btnBg: 'bg-indigo-700',
  tabActive: 'border-indigo-700 text-indigo-900 bg-indigo-50',
};

const processes: ProcessDef[] = [
  {
    id: 'customer-dispatch-sheet', no: '00', label: 'Customer Wise Dispatch Sheet', freq: 'Daily',
    icon: '📦', clause: 'IATF 8.5.2 / Dispatch & Traceability',
    desc: 'Daily update of customer-wise dispatch sheet — dispatch plan, part number, quantity, batch, and delivery status.',
    activities: ['Receive daily dispatch plan from production / planning', 'Update customer-wise dispatch sheet with part no., qty, batch, lot', 'Verify cleared OK status from OQC before dispatch', 'Cross-check dispatch qty against customer PO / schedule', 'Record actual dispatch date and lorry details', 'Archive signed dispatch sheet and share with logistics and customer quality'],
    docs: ['Customer-wise Dispatch Sheet', 'OQC Clearance Record', 'Dispatch Register', 'Customer PO / Schedule'],
    kpis: ['Dispatches Completed Today', 'Dispatch Accuracy %', 'Pending Dispatch (Holds)'],
  },
  {
    id: 'red-bin-ftt', no: '01', label: 'Red Bin Analysis & FTT', freq: 'Weekly',
    icon: '🔴', clause: 'IATF 8.7 / NC & FTT',
    desc: 'Weekly analysis of red bin rejections and First Time Through (FTT) rate — defect Pareto, trend, and corrective actions.',
    activities: ['Collect red bin data from all lines for the week', 'Categorize rejections by defect type, operation, and product', 'Calculate FTT %: (parts produced − rejections) / parts produced × 100', 'Prepare weekly Pareto of top 5 defects', 'Identify root cause for top defect and assign corrective action', 'Present red bin analysis and FTT trend in weekly quality meeting'],
    docs: ['Red Bin Analysis Report (Weekly)', 'FTT Tracker', 'Defect Pareto Chart', 'Corrective Action Log'],
    kpis: ['Weekly FTT %', 'Top Defect Category', 'Red Bin Count vs Previous Week'],
  },
  {
    id: 'customer-concern-eol', no: '02', label: 'Customer Concern Tracking — EOL Issue', freq: 'Weekly',
    icon: '🚨', clause: 'IATF 8.5.6 / Customer Concerns',
    desc: 'Weekly tracking of all customer concerns related to End-of-Line (EOL) failures — acknowledgement, CAPA, and closure.',
    activities: ['Review all open customer concerns from concern tracker', 'Map concern to EOL defect type and check sheet parameter', 'Verify if EOL parameter is in control plan and being checked', 'Update CAPA: tighten EOL check, add parameter, retrain operator', 'Submit concern response to customer with 8D / CAPA evidence', 'Close concern after customer acceptance and no recurrence in 90 days'],
    docs: ['Customer Concern Tracker', 'EOL Issue Analysis', '8D Response Sheet', 'Customer Acceptance Evidence'],
    kpis: ['Open Customer Concerns (EOL)', '8D On-Time Submission %', 'Concerns Closed This Week'],
  },
  {
    id: 'control-plan', no: '03', label: 'Control Plan (Incoming, Inprocess & EOL)', freq: 'Monthly',
    icon: '📋', clause: 'IATF 8.5 / Control Plan',
    desc: 'Monthly review and update of all three control plans — Incoming, In-Process, and End-of-Line — for all products.',
    activities: ['Pull latest revision of Incoming, In-Process, and EOL control plans', 'Cross-check each characteristic against current drawing revision', 'Update sampling frequency, gauge, and method if process changed', 'Add new characteristics if any customer complaint or PFMEA update', 'Obtain quality head and engineering sign-off on updated control plans', 'Distribute to IQC, IPQC, and EOL inspection stations'],
    docs: ['Incoming Control Plan', 'In-Process Control Plan', 'EOL Control Plan', 'Control Plan Revision Register'],
    kpis: ['Control Plans Reviewed', 'Control Plans Updated & Signed', 'Out-of-date Characteristics Found'],
  },
  {
    id: 'capability-spc', no: '04', label: 'Capability — SPC', freq: 'Monthly',
    icon: '📈', clause: 'IATF 8.5 / SPC & Capability',
    desc: 'Monthly SPC and process capability study for all critical-to-quality (CTQ) characteristics — Cp, Cpk review and action.',
    activities: ['Identify all CTQ characteristics requiring monthly capability study', 'Collect minimum 25 subgroups of measurement data', 'Plot X-bar R or I-MR control charts', 'Calculate Cp and Cpk — flag if Cpk < 1.33', 'Identify out-of-control signals (Nelson rules)', 'Issue process improvement action for Cpk < 1.33 characteristics'],
    docs: ['SPC Charts (Monthly — CTQ List)', 'Monthly Cpk Summary Report', 'Process Alert Log', 'Improvement Action Tracker'],
    kpis: ['CTQs with Monthly SPC', 'Cpk < 1.33 Count', 'SPC Actions Closed This Month'],
  },
  {
    id: 'eol-checksheet', no: '05', label: 'EOL Check Sheet & Actual Inspection', freq: 'Monthly',
    icon: '☑️', clause: 'IATF 8.5.1 / EOL Inspection',
    desc: 'Monthly review of EOL check sheets for completeness, adherence, and alignment with EOL control plan.',
    activities: ['Review all EOL check sheets in use for latest revision', 'Cross-check check sheet parameters vs EOL control plan', 'Spot-check 5 filled check sheets per inspector for completeness', 'Observe actual EOL inspection: method, gauge, recording', 'Identify gaps and brief EOL inspectors on corrections', 'Update check sheets if control plan or customer requirement changed'],
    docs: ['EOL Inspection Check Sheet (All Models)', 'EOL Control Plan Reference', 'Adherence Audit Record', 'Check Sheet Revision Log'],
    kpis: ['Check Sheets Reviewed', 'Adherence Score %', 'Check Sheets Updated This Month'],
  },
  {
    id: 'msa-rr', no: '06', label: 'R&R — MSA (Variable & Attributes)', freq: 'Monthly',
    icon: '📏', clause: 'AIAG MSA 4th Ed.',
    desc: 'Monthly Measurement System Analysis — Gauge R&R (variable) and Attribute Agreement Analysis (attribute) for all critical gauges.',
    activities: ['List all gauges requiring monthly MSA (new, modified, annual)', 'Plan Gauge R&R: select 10 parts, 3 appraisers, 2 trials', 'Conduct Variable Gauge R&R and calculate %GRR', 'Conduct Attribute Agreement Analysis for go/no-go and visual gauges', 'Flag %GRR > 30% for corrective action; 10–30% conditional', 'Update gauge master list with MSA status and %GRR result'],
    docs: ['Gauge R&R Data Sheet', 'Attribute Agreement Analysis Report', 'MSA Summary (Monthly)', 'Gauge Master List with MSA Status'],
    kpis: ['MSA Studies Completed', 'Gauges with %GRR > 30%', 'Attribute Gauges Passed AAA %'],
  },
  {
    id: 'instruments-calibration', no: '07', label: 'Measuring Instruments List & Calibration', freq: 'Monthly',
    icon: '🔧', clause: 'IATF 7.1.5 / Calibration',
    desc: 'Monthly review of all measuring instruments — calibration status, due dates, and calibration certificate filing.',
    activities: ['Generate list of all measuring instruments (master list)', 'Check calibration due date for each instrument', 'Send overdue instruments to calibration lab (internal or external)', 'Receive calibration certificates and verify accuracy', 'Tag instruments: Green (calibrated) / Red (out of calibration)', 'Update calibration schedule and master list with new due dates'],
    docs: ['Instrument Master List', 'Calibration Schedule', 'Calibration Certificates File', 'Overdue Instrument Log'],
    kpis: ['Instruments Calibration Due This Month', 'Instruments Overdue', 'Calibration Completion %'],
  },
  {
    id: 'ippm-trend', no: '08', label: 'IPPM Trend Chart & Action Plan', freq: 'Monthly',
    icon: '📉', clause: 'IATF 8.7 / IPPM Tracking',
    desc: 'Monthly In-Process PPM (IPPM) trend chart update and action plan — track defect rate per model per process.',
    activities: ['Calculate IPPM per model / operation: (rejected / produced) × 1,000,000', 'Update monthly IPPM trend chart (rolling 12 months)', 'Identify models or operations with worsening IPPM trend', 'Prepare action plan for top IPPM contributors', 'Track action plan implementation and verify IPPM improvement', 'Present IPPM trend chart in monthly quality review meeting'],
    docs: ['Monthly IPPM Trend Chart', 'IPPM Tracker (Model-wise)', 'IPPM Action Plan', 'Monthly Quality Review Presentation'],
    kpis: ['Overall Plant IPPM', 'Models Above IPPM Target', 'IPPM Trend vs Previous Month'],
  },
  {
    id: 'model-quality-plan', no: '09', label: 'Model-wise Quality Plan', freq: 'Monthly',
    icon: '🗂️', clause: 'IATF 8.5 / Quality Plan',
    desc: 'Monthly review and update of model-wise quality plans — inspection parameters, frequency, tooling, and acceptance criteria per model.',
    activities: ['List all active models in production with their quality plan', 'Review each quality plan against latest drawing and control plan', 'Update quality plan for new models entering production', 'Revise parameters if customer concern or audit finding requires', 'Obtain sign-off on updated quality plans from quality head', 'Distribute to all inspection stations and archive previous revision'],
    docs: ['Model-wise Quality Plan (all models)', 'Drawing Reference per Model', 'Quality Plan Revision Register', 'Distribution Acknowledgement'],
    kpis: ['Quality Plans Reviewed', 'Quality Plans Updated', 'Models Without Current Quality Plan'],
  },
  {
    id: 'plant-layout', no: '10', label: 'Plant Layout', freq: 'Monthly',
    icon: '🏭', clause: 'IATF 8.5.1 / Plant Layout',
    desc: 'Monthly review and update of plant layout — machine locations, flow, quality checkpoints, and safety zones.',
    activities: ['Review current plant layout drawing for accuracy', 'Verify any machine movements or new additions are reflected', 'Mark quality inspection checkpoints on updated layout', 'Identify any flow improvement opportunities (lean layout)', 'Update plant layout drawing with revision number and date', 'Post updated plant layout at production entry and quality office'],
    docs: ['Plant Layout Drawing (Current Rev)', 'Layout Change Request Form', 'Layout Revision Register', 'Layout Approval Sign-off'],
    kpis: ['Layout Updated This Month', 'Layout Changes Made', 'Inspection Checkpoints Marked'],
  },
  {
    id: 'scrap-data', no: '11', label: 'Scrap Data', freq: 'Weekly',
    icon: '🗑️', clause: 'IATF 8.7 / Scrap Tracking',
    desc: 'Weekly collection, analysis, and reporting of scrap data — quantity, cost, defect type, and model-wise breakdown.',
    activities: ['Collect scrap count and weight from all lines for the week', 'Categorize scrap by defect type, model, and operation', 'Calculate scrap cost: quantity × material cost per unit', 'Prepare weekly scrap Pareto (top 5 defect causes)', 'Identify opportunities to reduce scrap (process, material, tooling)', 'Report weekly scrap data to production head and quality head'],
    docs: ['Weekly Scrap Report', 'Scrap Register (Line-wise)', 'Scrap Cost Calculation Sheet', 'Scrap Pareto Chart'],
    kpis: ['Weekly Scrap Quantity (Units)', 'Weekly Scrap Cost (INR)', 'Top Scrap Defect Category'],
  },
  {
    id: 'plant-4m-changes', no: '12', label: 'Plant 4M Changes', freq: 'Monthly',
    icon: '🔄', clause: 'IATF 8.5.6 / Change Management',
    desc: 'Monthly review and control of all plant 4M changes — Man, Machine, Material, Method — and their quality impact.',
    activities: ['Collect all 4M change requests for the month', 'Classify change: Man (new operator), Machine (repair/new), Material (grade change), Method (process change)', 'Assess quality impact and decide if trial / PPAP required', 'Conduct first-off approval after 4M change before mass production', 'Document change in 4M change register with date and approver', 'Notify customer if 4M change affects product characteristics'],
    docs: ['4M Change Request Form', '4M Change Register', 'First-Off Approval After 4M Change', 'Customer Notification (if required)'],
    kpis: ['4M Changes This Month', '4M Changes with Customer Notification', '4M Changes Requiring Trial / PPAP'],
  },
  {
    id: 'fg-layout-inspection', no: '13', label: 'FG Seat Layout Inspection', freq: 'Monthly',
    icon: '🪑', clause: 'IATF 8.5 / Layout Inspection',
    desc: 'Monthly 100% dimensional layout inspection of finished goods (FG) seat — all drawing dimensions verified against tolerance.',
    activities: ['Select FG seat model for monthly layout inspection (rotate models)', 'Perform 100% dimensional check against drawing (all ballooned dimensions)', 'Check functional parameters: foam hardness, cover tension, frame geometry', 'Record all results in layout inspection report', 'Flag any out-of-tolerance dimension for immediate corrective action', 'File signed layout report and update layout inspection tracker'],
    docs: ['FG Seat Layout Inspection Report', 'Ballooned Drawing', 'Layout Inspection Tracker', 'Corrective Action Log (for deviations)'],
    kpis: ['Layout Inspections Completed', 'Dimensions Out of Tolerance', 'Models Covered This Month'],
  },
  {
    id: 'appearance-manual-fg', no: '14', label: 'Appearance Manual — FG Seat', freq: 'Monthly',
    icon: '🎨', clause: 'IATF 8.5.1 / Appearance Criteria',
    desc: 'Monthly review and update of FG seat appearance inspection manual — visual standards, limit samples, defect catalogue.',
    activities: ['Review FG seat appearance manual for current defect definitions', 'Update defect photos and descriptions if new defect types found', 'Check limit samples at EOL inspection station — replace if worn', 'Brief EOL inspectors on any updated appearance criteria', 'Obtain quality head sign-off on updated appearance manual', 'Archive previous version with effective date and issue new copy to EOL'],
    docs: ['FG Seat Appearance Inspection Manual', 'Defect Photo Catalogue', 'Limit Sample Log', 'Manual Revision Register'],
    kpis: ['Appearance Manual Reviewed', 'Defect Photos Updated', 'Limit Samples Replaced / Renewed'],
  },
  {
    id: 'eol-skill-assessment', no: '15', label: 'EOL Skill Assessment', freq: 'Monthly',
    icon: '👥', clause: 'IATF 7.2 / Competence',
    desc: 'Monthly skill assessment of all EOL (End-of-Line) inspectors — visual inspection, gauge use, reporting, and defect identification.',
    activities: ['List all EOL inspectors and their current competency level', 'Assess each inspector: defect identification test, gauge operation, check sheet filling', 'Score each inspector (pass mark ≥ 80%)', 'Identify gaps and schedule on-job training for below-standard inspectors', 'Update EOL skill matrix with latest assessment results', 'Get quality head sign-off on updated skill matrix'],
    docs: ['EOL Skill Matrix', 'Inspector Assessment Sheet', 'Defect Identification Test Paper', 'Training Record (for gaps)'],
    kpis: ['EOL Inspectors Assessed', 'Inspectors Below 80% Score', 'Training Actions Initiated'],
  },
  {
    id: 'rework-pfmea-ods-wi', no: '16', label: 'Rework PFMEA, ODS & WI', freq: 'Monthly',
    icon: '🔧', clause: 'IATF 8.7.1 / Rework Control',
    desc: 'Monthly review and update of Rework Process FMEA, Operation Defect Standards (ODS), and Work Instructions for all rework operations.',
    activities: ['Review Rework PFMEA for all active rework types', 'Update PFMEA if new rework type or failure mode found', 'Review ODS for each rework: defect accept/reject criteria clear', 'Update Work Instructions (WI) for any rework method change', 'Train rework operators on updated ODS / WI', 'Obtain sign-off and file all updated rework documents'],
    docs: ['Rework PFMEA', 'Operation Defect Standard (ODS)', 'Rework Work Instruction (WI)', 'Document Revision Register'],
    kpis: ['Rework PFMEAs Reviewed', 'ODS / WI Updated', 'Rework Operators Trained on Updates'],
  },
  {
    id: 'ods-sop', no: '17', label: 'ODS — SOP', freq: 'Monthly',
    icon: '📄', clause: 'IATF 8.5.1 / Standard Operating Procedure',
    desc: 'Monthly review and update of all Operation Defect Standards (ODS) and Standard Operating Procedures (SOP) at all workstations.',
    activities: ['List all ODS and SOPs in use across production lines', 'Review each document for accuracy vs current process and drawing', 'Update ODS if new defect type or acceptance criteria changed', 'Update SOP if process method, tooling, or sequence changed', 'Post revised ODS / SOP at respective workstation', 'Conduct operator briefing on any updated ODS / SOP'],
    docs: ['ODS Master Register', 'SOP Master Register', 'ODS / SOP Revision Log', 'Operator Briefing Record'],
    kpis: ['ODS Reviewed This Month', 'SOPs Updated', 'Operators Briefed on Changes'],
  },
  {
    id: 'process-control-sheet', no: '18', label: 'Process Control Sheet', freq: 'Monthly',
    icon: '📋', clause: 'IATF 8.5.1 / Process Control',
    desc: 'Monthly review and update of Process Control Sheets at all operations — machine parameters, settings, and critical controls.',
    activities: ['Pull all process control sheets (one per operation / machine)', 'Verify process settings on control sheet match actual machine settings', 'Update parameters if process was optimized or changed', 'Cross-check control sheet with PFMEA and control plan', 'Post updated process control sheet at machine', 'Record revision and file master copy in document control'],
    docs: ['Process Control Sheet (Per Operation)', 'Machine Parameter Reference', 'PFMEA Cross-Reference', 'Document Control Register'],
    kpis: ['Process Control Sheets Reviewed', 'Sheets with Setting Deviations Found', 'Sheets Updated & Posted'],
  },
  {
    id: 'pokayoke-tracking', no: '19', label: 'Poka-Yoke Control & Tracking', freq: 'Weekly',
    icon: '🔒', clause: 'IATF 8.5.1 / Error Proofing',
    desc: 'Weekly challenge and verification of all poka-yoke and error-proofing devices on production lines.',
    activities: ['List all poka-yoke devices with location and challenge method', 'Challenge each device with a known NG part or condition', 'Record pass/fail result in poka-yoke challenge register', 'Halt line immediately if critical poka-yoke fails challenge', 'Arrange maintenance / repair; re-challenge before restarting line', 'Update poka-yoke tracker and report any failed devices to quality head'],
    docs: ['Poka-Yoke Master List', 'Weekly Challenge Register', 'Poka-Yoke Failure Report', 'Maintenance Repair Record'],
    kpis: ['Poka-Yoke Devices Challenged This Week', 'Devices Failed Challenge', 'Devices Repaired & Restored'],
  },
  {
    id: 'alternative-method', no: '20', label: 'Alternative Method', freq: 'Monthly',
    icon: '🔀', clause: 'IATF 8.5.1 / Alternative Control',
    desc: 'Monthly review and management of alternative inspection / production methods used when primary method is unavailable.',
    activities: ['Identify all operations with defined alternative methods (gauge/process backup)', 'Review if alternative method is still valid and documented', 'Verify alternative method gives equivalent results to primary (correlation study if needed)', 'Ensure operators are trained on the alternative method', 'Record use of alternative methods in production log when triggered', 'Review and update alternative method register monthly'],
    docs: ['Alternative Method Register', 'Correlation Study Report', 'Alternative Method Procedure', 'Usage Log'],
    kpis: ['Alternative Methods Defined', 'Alternative Methods Reviewed', 'Times Alternative Method Used This Month'],
  },
  {
    id: 'traceability-stickers', no: '21', label: 'Traceability Management & Stickers', freq: 'Daily',
    icon: '🏷️', clause: 'IATF 8.5.2 / Traceability',
    desc: 'Daily management of product traceability — batch sticker application, lot tracking, serial number control, and traceability record.',
    activities: ['Verify traceability stickers are applied to all products / pallets at EOL', 'Check sticker content: model, part no., batch, date, shift, inspector', 'Confirm batch number is linked to production record in system', 'Investigate any missing or incorrect stickers immediately', 'Retain traceability records as per customer and regulatory requirement', 'Update traceability log and verify recall capability monthly'],
    docs: ['Traceability Sticker Format', 'Batch / Lot Traceability Register', 'Production Record Link', 'Recall Drill Record'],
    kpis: ['Products with Traceability Sticker %', 'Traceability Errors Found Today', 'Batch Records Retained (Months)'],
  },
  {
    id: 'local-master-list', no: '22', label: 'Local Master List', freq: 'Monthly',
    icon: '📁', clause: 'IATF 7.5 / Document Control',
    desc: 'Monthly update of the Local Master List — all controlled documents at the plant level, revision status, and location.',
    activities: ['Review Local Master List for all plant-level controlled documents', 'Verify current revision on master list matches issued documents', 'Add new documents created this month to master list', 'Remove or mark obsolete any withdrawn documents', 'Confirm all documents are accessible to relevant personnel', 'Obtain document controller sign-off on updated master list'],
    docs: ['Local Master List (Current Rev)', 'Document Revision Log', 'Obsolete Document Register', 'Document Controller Sign-off'],
    kpis: ['Documents in Local Master List', 'New Documents Added This Month', 'Obsolete Documents Removed'],
  },
  {
    id: 'external-master-list', no: '23', label: 'External Master List', freq: 'Monthly',
    icon: '🌐', clause: 'IATF 7.5 / External Documents',
    desc: 'Monthly update of the External Master List — customer drawings, standards (IATF, AIAG, ISO), and external specifications.',
    activities: ['Review External Master List for all customer drawings and standards', 'Check for drawing revision updates from customers (portal / mail)', 'Update external master list with latest revision for each document', 'Withdraw and mark obsolete superseded drawings or standards', 'Verify critical external documents are available at point of use', 'Obtain sign-off on updated external master list'],
    docs: ['External Master List (Current Rev)', 'Customer Drawing Revision Log', 'Standards / Specifications Register', 'Obsolete External Documents Log'],
    kpis: ['External Documents in Master List', 'Drawings Updated This Month', 'Obsolete External Documents Removed'],
  },
  {
    id: 'doc-control-retention', no: '24', label: 'Control & Retention of Documents', freq: 'Monthly',
    icon: '🗄️', clause: 'IATF 7.5.3 / Record Retention',
    desc: 'Monthly review of document control and retention compliance — ensure records are stored, retained for required period, and retrievable.',
    activities: ['Audit physical and digital document storage locations', 'Verify retention period compliance for all quality records', 'Identify records nearing retention end date — decide retain or dispose', 'Ensure records are protected from damage, loss, and unauthorized access', 'Verify backup of digital quality records exists', 'Update document retention schedule and report status'],
    docs: ['Document Retention Schedule', 'Record Storage Audit Report', 'Retention Compliance Summary', 'Disposal Authorization Form'],
    kpis: ['Records Audited This Month', 'Non-compliant Storage Found', 'Records Disposed (Expired Retention)'],
  },
  {
    id: 'inhouse-deviation', no: '25', label: 'In-house Deviation', freq: 'Weekly',
    icon: '⚠️', clause: 'IATF 8.7.3 / Deviation / Concession',
    desc: 'Weekly tracking of all in-house deviations (concessions) — process or product deviations from specification, limited to agreed quantity and time.',
    activities: ['Identify parts / process requiring deviation from standard specification', 'Raise In-house Deviation Request with justification and scope', 'Get engineering and quality head approval before production proceeds', 'Define limited approval: quantity, validity period, and monitoring conditions', 'Log deviation in deviation register with approver and expiry', 'Monitor closed deviation — confirm no recurrence and standard restored'],
    docs: ['In-house Deviation Request Form', 'Deviation Register', 'Engineering Approval Evidence', 'Deviation Closure Record'],
    kpis: ['Active Deviations This Week', 'Deviations Expiring Soon', 'Deviations Closed This Week'],
  },
];

export default function ProcessQualityPage() {
  return <DepartmentPageTemplate dept={dept} processes={processes} />;
}
